[package]
name = "atcoder"
version = "0.1.0"
authors = ["hamap"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"  
rand = "0.7.3"  
proconio = "0.3.8"
itertools = "0.10.5"